name: 'Check permissions'
description: 'Check a list of permissions and fail when any one does'
author: 'LoveIsGrief'
inputs:
  config_file:
    required: true
    description: 'A YAML file with a list of permissions and their args'
    default: ".github/permissions.yml"
  token:
    required: true
    description: 'The github token to be used when making API requests'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: orange
  icon: x-octagon
